resource_group_name     = "rg-hyango-web-sql-db"
resource_group_location = "westeurope"
app_service_plan_name   = "appseiceplan-web-21"
app_service_name        = "terra-web-021"
sql_server_name         = "terra-sqlserver-021"
sql_database_name       = "ProductsDB"
sql_admin_login         = "user01"
sql_admin_password      = "@Aa123456789!"
